### ISSUE TITLE
HW Decorder not working in Galaxy S4 Mini (stagefright error)

### ISSUE THREAD

**Issue by ghost** [DirtyUnicorns/android_frameworks_av#1]
logcat:
`01-03 03:59:52.756  1886  1908 V AlarmClock: AlarmInitReceiver - Reset timers and clear stopwatch data

01-03 03:59:52.763   726   860 D PowerHAL: power_hint: no power profile selected yet

01-03 03:59:52.763   726   860 D PowerHAL: power_hint: no power profile selected yet

01-03 03:59:52.844   726  1917 I OMXClient: Using client-side OMX mux.

01-03 03:59:52.844   726  1917 E ACodec  : Unable to instantiate a decoder for type 'audio/vorbis' with err 0xfffffffe.

01-03 03:59:52.844   726  1917 E ACodec  : signalError(omxError 0xfffffffe, internalError -2)

01-03 03:59:52.844   726  1917 E MediaCodec: Codec reported err 0xfffffffe, actionCode 0, while in state 1

01-03 03:59:52.845   726  1913 E SoundPool: Unable to load sample

01-03 03:59:52.857   726   914 W AudioService: onLoadSoundEffects(), Error -2147483648 while loading samples

01-03 03:59:52.876   726  1920 I OMXClient: Using client-side OMX mux.

01-03 03:59:52.877   726  1920 E ACodec  : Unable to instantiate a decoder for type 'audio/vorbis' with err 0xfffffffe.

01-03 03:59:52.877   726  1920 E ACodec  : signalError(omxError 0xfffffffe, internalError -2)

01-03 03:59:52.877   726  1920 E MediaCodec: Codec reported err 0xfffffffe, actionCode 0, while in state 1

01-03 03:59:52.879   726  1913 E SoundPool: Unable to load sample

01-03 03:59:52.925  1886  1908 V AlarmClock: AlarmInitReceiver finished

01-03 03:59:52.929   726  1380 I ActivityManager: Start proc 1923:com.android.email/u0a35 for broadcast com.android.email/.service.EmailBroadcastReceiver

01-03 03:59:53.012   213   262 I ThermalDaemon: Sensor 'tsens_tz_sensor9' - alarm raised 2 at 91.0 degC

01-03 03:59:53.012   213   262 I ThermalDaemon: ACTION: CPU - Setting CPU[0] to 1566000

01-03 03:59:53.013   213   262 I ThermalDaemon: ACTION: CPU - Setting CPU[1] to 1566000

01-03 03:59:53.100  1923  1923 W System  : ClassLoader referenced unknown path: /system/app/Email/lib/arm

01-03 03:59:53.218   188   188 I rmt_storage: rmt_storage_connect_cb: clnt_h=0x19 conn_h=0xb6c4a010

01-03 03:59:53.218   188   188 I rmt_storage: rmt_storage_open_cb: /boot/modem_fs1: clnt_h=0x19: req_h=0x28 msg_id=1: Client found

01-03 03:59:53.219   188   188 I rmt_storage: rmt_storage_open_cb: /boot/modem_fs1: clnt_h=0x19: req_h=0x28 msg_id=1: Send response: res=0 err=0

01-03 03:59:53.219   188   188 I rmt_storage: rmt_storage_connect_cb: clnt_h=0x1a conn_h=0xb6c4a018`

**Comment by nychitman1** [comment]
Being that this device is not supported, I would recommend finding the fix and pushing it to our gerrit.
